# Manipulação EDA da base de dados Titanic

## Importando pacotes e bibliotecas

In [2]:
from matplotlib import pyplot as plt
import seaborn as sas
import pandas as pd
import numpy as np
#---
from utils.tratar_dados import *
from utils.funcoes_graficas import *

## Importando base de dados

### Importando de um .csv

In [3]:
file_name = "titanic"
titanic_dataframe = read_data(file_name)

Read from .pkl file format


### Importando de um .pkl

In [4]:
file_name = "titanic"
titanic_dataframe = read_data(file_name)

Read from .pkl file format


## Tratamento dos dados

### Passando os títulos para minúsculo

In [5]:
titulos = titanic_dataframe.columns
titulos = fix_header_to_standarts(titulos)
titanic_dataframe.columns = titulos

### Remoção de espaços

In [6]:
# Nao foi necessario

### Remoção de caracteres proibidos

In [7]:
# Nao foi necessario

### Normalização dos dados

In [8]:
titanic_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  418 non-null    int64  
 1   survived     418 non-null    int64  
 2   pclass       418 non-null    int64  
 3   name         418 non-null    object 
 4   sex          418 non-null    object 
 5   age          332 non-null    float64
 6   sibsp        418 non-null    int64  
 7   parch        418 non-null    int64  
 8   ticket       418 non-null    object 
 9   fare         417 non-null    float64
 10  cabin        91 non-null     object 
 11  embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


In [9]:
titanic_dataframe.sample(10)

passengerid  survived  pclass                                       name  \
104          996         1       3  Thomas, Mrs. Alexander (Thamine Thelma")"   
76           968         0       3                           Miles, Mr. Frank   
319         1211         0       2               Jefferys, Mr. Ernest Wilfred   
41           933         0       1                Franklin, Mr. Thomas Parham   
129         1021         0       3                       Petersen, Mr. Marius   
29           921         0       3                          Samaan, Mr. Elias   
355         1247         0       1                   Julian, Mr. Henry Forbes   
206         1098         1       3                   McGowan, Miss. Katherine   
85           977         0       3                         Khalil, Mr. Betros   
54           946         0       2          Mangiavacchi, Mr. Serafino Emilio   

        sex   age  sibsp  parch       ticket     fare cabin embarked  
104  female  16.0      1      1         2625   8.5167   NaN        C  
76     male   NaN      0      0       359306   8.0500   NaN        S  
319    male  22.0      2      0   C.A. 31029  31.5000   NaN        S  
41     male   NaN      0      0       113778  26.5500   D34        S  
129    male  24.0      0      0       342441   8.0500   NaN        S  
29     male   NaN      2      0         2662  21.6792   NaN        C  
355    male  50.0      0      0       113044  26.0000   E60        S  
206  female  35.0      0      0         9232   7.7500   NaN        Q  
85     male   NaN      1      0         2660  14.4542   NaN        C  
54     male   NaN      0      0  SC/A.3 2861  15.5792   NaN        C

#### Tratamento de NaNs

##### Coluna "cabin"

In [10]:
coluna_cabine = "cabin"
for coluna in titanic_dataframe.columns:
    if coluna_cabine == coluna:
        titanic_dataframe[f"{coluna}"] = titanic_dataframe[f"{coluna}"].fillna("unknown")


titanic_dataframe.sample(5)

passengerid  survived  pclass  \
306         1198         0       1   
13           905         0       2   
165         1057         1       3   
171         1063         0       3   
74           966         1       1   

                                           name     sex   age  sibsp  parch  \
306        Allison, Mr. Hudson Joshua Creighton    male  30.0      1      2   
13                         Howard, Mr. Benjamin    male  63.0      1      0   
165  Kink-Heilmann, Mrs. Anton (Luise Heilmann)  female  26.0      1      1   
171                         Zakarian, Mr. Ortin    male  27.0      0      0   
74                         Geiger, Miss. Amalie  female  35.0      0      0   

     ticket     fare    cabin embarked  
306  113781  151.550  C22 C26        S  
13    24065   26.000  unknown        S  
165  315153   22.025  unknown        S  
171    2670    7.225  unknown        C  
74   113503  211.500     C130        C

In [11]:
titanic_dataframe.cabin = fix_header_to_standarts(titanic_dataframe.cabin.values)

##### Coluna "age"

In [12]:
coluna_cabine = "age"
media = int(round(titanic_dataframe.age.mean(), 0))

for coluna in titanic_dataframe.columns:
    if coluna_cabine == coluna:
        titanic_dataframe[f"{coluna}"] = titanic_dataframe[f"{coluna}"].fillna(media)


titanic_dataframe.sample(5)

passengerid  survived  pclass  \
202         1094         0       1   
364         1256         1       1   
390         1282         0       1   
346         1238         0       2   
199         1091         1       3   

                                             name     sex   age  sibsp  parch  \
202                        Astor, Col. John Jacob    male  47.0      1      0   
364  Harder, Mrs. George Achilles (Dorothy Annan)  female  25.0      1      0   
390                    Payne, Mr. Vivian Ponsonby    male  23.0      0      0   
346                    Botsford, Mr. William Hull    male  26.0      0      0   
199       Rasmussen, Mrs. (Lena Jacobsen Solvang)  female  30.0      0      0   

       ticket      fare    cabin embarked  
202  PC 17757  227.5250  c62_c64        C  
364     11765   55.4417      e50        C  
390     12749   93.5000      b24        S  
346    237670   13.0000  unknown        S  
199     65305    8.1125  unknown        S

##### Coluna "embarked"

In [13]:
titanic_dataframe.embarked.unique()

array(['Q', 'S', 'C'], dtype=object)

In [14]:
# NAO EXECUTE ESSA CELUNA MAIS DE UMA UNICA VEZ
titanic_dataframe.embarked = titanic_dataframe.embarked.map({
    "C": 0,
    "Q": 1,
    "S": 2
    }
)

In [15]:
titanic_dataframe.sample(5)

passengerid  survived  pclass                              name     sex  \
357         1249         0       3               Lockyer, Mr. Edward    male   
302         1194         0       2       Phillips, Mr. Escott Robert    male   
1            893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   
324         1216         1       1            Kreuchen, Miss. Emilie  female   
102          994         0       3                Foley, Mr. William    male   

      age  sibsp  parch       ticket      fare    cabin  embarked  
357  30.0      0      0         1222    7.8792  unknown         2  
302  43.0      0      1  S.O./P.P. 2   21.0000  unknown         2  
1    47.0      1      0       363272    7.0000  unknown         2  
324  39.0      0      0        24160  211.3375  unknown         2  
102  30.0      0      0       365235    7.7500  unknown         1

##### Coluna "sex"

In [16]:
titanic_dataframe.sex.unique()

array(['male', 'female'], dtype=object)

In [17]:
# NAO EXECUTE ESSA CELUNA MAIS DE UMA UNICA VEZ
titanic_dataframe.sex = titanic_dataframe.sex.map({
    "male": 0,
    "female": 1
    }
)

In [18]:
titanic_dataframe.sample(5)

passengerid  survived  pclass  \
227         1119         1       3   
181         1073         0       1   
2            894         0       2   
22           914         1       1   
24           916         1       1   

                                                name  sex   age  sibsp  parch  \
227                           McNeill, Miss. Bridget    1  30.0      0      0   
181                 Compton, Mr. Alexander Taylor Jr    0  37.0      1      1   
2                          Myles, Mr. Thomas Francis    0  62.0      0      0   
22              Flegenheim, Mrs. Alfred (Antoinette)    1  30.0      0      0   
24   Ryerson, Mrs. Arthur Larned (Emily Maria Borie)    1  48.0      1      3   

       ticket      fare            cabin  embarked  
227    370368    7.7500          unknown         1  
181  PC 17756   83.1583              e52         0  
2      240276    9.6875          unknown         1  
22   PC 17598   31.6833          unknown         2  
24   PC 17608  262.3750  b57_b59_b63_b66         0

#### Tratamento de tipos

In [19]:
id_max = titanic_dataframe.passengerid.max()
fare_max = round(titanic_dataframe.fare.max(), 2)
print(f"O maior id é:\t\t{id_max}\nA maior tarifa é:\t{fare_max}\n")

O maior id é:		1309
A maior tarifa é:	512.33



In [20]:
### coluna passengerid
titanic_dataframe.passengerid = titanic_dataframe.passengerid.astype("uint16")

### coluna survided
titanic_dataframe.survived = titanic_dataframe.survived.astype("uint8")

### coluna pclass
titanic_dataframe.pclass = titanic_dataframe.pclass.astype("uint8")

### coluna name
titanic_dataframe.name = titanic_dataframe.name.astype("category")

### coluna sex
titanic_dataframe.sex = titanic_dataframe.sex.astype("uint8")

### coluna age
titanic_dataframe.age = titanic_dataframe.age.astype("uint8")

### coluna sibsp
titanic_dataframe.sibsp = titanic_dataframe.sibsp.astype("uint8")

### coluna parch
titanic_dataframe.parch = titanic_dataframe.parch.astype("uint8")

### coluna ticket
titanic_dataframe.ticket = titanic_dataframe.ticket.astype("category")

### coluna fare
titanic_dataframe.fare = titanic_dataframe.fare.astype("float16")
# titanic_dataframe.fare = titanic_dataframe["fare"].apply(np.floor)

### coluna cabin
titanic_dataframe.cabin = titanic_dataframe.cabin.astype("category")

### coluna embarked
titanic_dataframe.embarked = titanic_dataframe.embarked.astype("uint8")

In [21]:
titanic_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   passengerid  418 non-null    uint16  
 1   survived     418 non-null    uint8   
 2   pclass       418 non-null    uint8   
 3   name         418 non-null    category
 4   sex          418 non-null    uint8   
 5   age          418 non-null    uint8   
 6   sibsp        418 non-null    uint8   
 7   parch        418 non-null    uint8   
 8   ticket       418 non-null    category
 9   fare         417 non-null    float16 
 10  cabin        418 non-null    category
 11  embarked     418 non-null    uint8   
dtypes: category(3), float16(1), uint16(1), uint8(7)
memory usage: 39.7 KB


#### Exclusão de colunas inconclusívas

##### Coluna "name"

In [22]:
titanic_dataframe = titanic_dataframe.drop(["name"], axis=1)
titanic_dataframe.sample(5)

passengerid  survived  pclass  sex  age  sibsp  parch  \
325         1217         0       3    0   23      0      0   
31           923         0       2    0   24      2      0   
20           912         0       1    0   55      1      0   
22           914         1       1    1   30      0      0   
85           977         0       3    0   30      1      0   

                 ticket       fare    cabin  embarked  
325  SOTON/O.Q. 3101309   7.050781  unknown         2  
31           C.A. 31029  31.500000  unknown         2  
20             PC 17603  59.406250  unknown         0  
22             PC 17598  31.687500  unknown         2  
85                 2660  14.453125  unknown         0

##### Coluna "ticket"

In [23]:
titanic_dataframe = titanic_dataframe.drop(["ticket"], axis=1)
titanic_dataframe.sample(5)

passengerid  survived  pclass  sex  age  sibsp  parch       fare  \
85           977         0       3    0   30      1      0  14.453125   
67           959         0       1    0   47      0      0  42.406250   
225         1117         1       3    1   30      0      2  15.242188   
9            901         0       3    0   21      2      0  24.156250   
125         1017         1       3    1   17      0      1  16.093750   

       cabin  embarked  
85   unknown         0  
67   unknown         2  
225  unknown         0  
9    unknown         2  
125  unknown         2

##### Coluna "cabin"

In [24]:
titanic_dataframe = titanic_dataframe.drop(["cabin"], axis=1)
titanic_dataframe.sample(5)

passengerid  survived  pclass  sex  age  sibsp  parch       fare  \
48           940         1       1    1   60      0      0  76.312500   
151         1043         0       3    0   30      0      0   7.894531   
233         1125         0       3    0   30      0      0   7.878906   
175         1067         1       2    1   15      0      2  39.000000   
234         1126         0       1    0   39      1      0  71.312500   

     embarked  
48          0  
151         0  
233         1  
175         2  
234         0

#### Resultado final

In [25]:
titanic_dataframe.info()

# Se quiser salvar descomentar bloco a seguir
#
#
# file_name = "titanic"
# save_pkl_file(titanic_dataframe, file_name)
#
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  418 non-null    uint16 
 1   survived     418 non-null    uint8  
 2   pclass       418 non-null    uint8  
 3   sex          418 non-null    uint8  
 4   age          418 non-null    uint8  
 5   sibsp        418 non-null    uint8  
 6   parch        418 non-null    uint8  
 7   fare         417 non-null    float16
 8   embarked     418 non-null    uint8  
dtypes: float16(1), uint16(1), uint8(7)
memory usage: 4.6 KB


## Extração dos dados

### Média

#### Coluna "age"

In [26]:
media_idade = round(titanic_dataframe.age.mean(), ndigits=1)
print(f"A média de idade é: {media_idade}\n")

A média de idade é: 30.2



#### Coluna "fare"

In [27]:
media_taxa = round(titanic_dataframe.fare.mean(), ndigits=2)
print(f"A média de taxa é: {media_taxa}\n")

A média de taxa é: 35.625



### Mediana

#### Coluna "age"

In [28]:
mediana_idade = titanic_dataframe.age.median()
print(f"A mediana de idade é: {mediana_idade}\n")

A mediana de idade é: 30.0



#### Coluna "fare"

In [29]:
mediana_taxa = titanic_dataframe.fare.median()
print(f"A mediana de taxa é: {round(mediana_taxa, 0)}\n")

A mediana de taxa é: 14.0



### Moda

#### Coluna "age"

In [30]:
moda_idade = titanic_dataframe.age.mode()
print(f"A moda de idade é: {moda_idade}\n")

A moda de idade é: 0    30
Name: age, dtype: uint8



#### Coluna "fare"

In [31]:
moda_taxa = titanic_dataframe.fare.mode()
print(f"A moda de taxa é: {moda_taxa}\n")

A moda de taxa é: 0    7.75
Name: fare, dtype: float16



### Desvio padrão

#### Coluna "age"

In [32]:
desvio_padrao_idade = round(titanic_dataframe.age.std(), 2)

if desvio_padrao_idade == np.Inf:
    print(f"O desvio padrão da idade é infinito\n")
else:
    print(f"O desvio padrão da idade é: {desvio_padrao_idade}\n")

O desvio padrão da idade é: 12.65



#### Coluna "fare"

In [33]:
desvio_padrao_taxa = round(titanic_dataframe.fare.std(), 2)

if desvio_padrao_taxa == np.Inf:
    print(f"O desvio padrão da taxa é infinito\n")
else:    
    print(f"O desvio padrão da taxa é: {desvio_padrao_taxa}\n")

O desvio padrão da taxa é infinito



### Mínimo

#### Coluna "age"

In [34]:
print(f"O passageiro mais novo tinha {titanic_dataframe.age.min()} anos de idade\n")

O passageiro mais novo tinha 0 anos de idade



#### Coluna "fare"

In [48]:
print(f"O passagem mais barata custou US$ {titanic_dataframe.fare.min()}\n")

O passagem mais barata custou US$ 0.0



### Máximo

#### Coluna "age"

In [ ]:
print(f"O passageiro mais velho tinha {titanic_dataframe.age.max()} anos de idade\n")

#### Coluna "fare"

In [49]:
print(f"O passagem mais cara custou US$ {titanic_dataframe.fare.max()}\n")

O passagem mais cara custou US$ 512.5



### Somatório do preço de todas as passagens

#### sum()

In [56]:
somatorio_passagens = titanic_dataframe.fare.sum()
print(f"O somatório do preço de todas as passagenes é: US$ {somatorio_passagens}\n")

O somatório do preço de todas as passagenes é: US$ 14856.0



### Contagem (Count)

#### Coluna "survived"

In [35]:
titanic_dataframe.survived.unique()

array([0, 1], dtype=uint8)

In [36]:
qtd_mortes = titanic_dataframe.survived.value_counts()[1]
qtd_vivos = titanic_dataframe.survived.value_counts()[0]

print(f"O números de sobreviventes é:\t{qtd_vivos}\nO número de mortos é:\t\t{qtd_mortes}\n")

O números de sobreviventes é:	266
O número de mortos é:		152



#### Coluna "pclass"

In [37]:
titanic_dataframe.pclass.unique()

array([3, 2, 1], dtype=uint8)

In [38]:
qtd_classe_1 = titanic_dataframe.pclass.value_counts()[1]
qtd_classe_2 = titanic_dataframe.pclass.value_counts()[2]
qtd_classe_3 = titanic_dataframe.pclass.value_counts()[3]

print(f"O números de pessoas na classe 1 é: {qtd_classe_1}\nO números de pessoas na classe 2 é: {qtd_classe_2}\nO números de pessoas na classe 3 é: {qtd_classe_3}\n")

O números de pessoas na classe 1 é: 107
O números de pessoas na classe 2 é: 93
O números de pessoas na classe 3 é: 218



#### Coluna "sex"

In [39]:
titanic_dataframe.sex.unique()

array([0, 1], dtype=uint8)

In [40]:
qtd_homens = titanic_dataframe.sex.value_counts()[0]
qtd_mulheres = titanic_dataframe.sex.value_counts()[1]

print(f"O números de mulheres é:\t{qtd_mulheres}\nO número de homens é:\t\t{qtd_homens}\n")

O números de mulheres é:	152
O número de homens é:		266



#### Coluna "sibsp"

In [41]:
titanic_dataframe.sibsp.unique()

array([0, 1, 2, 3, 4, 5, 8], dtype=uint8)

In [42]:
qtd_solo = titanic_dataframe.sibsp.value_counts()[0]
qtd_par = titanic_dataframe.sibsp.value_counts()[1]
qtd_trio = titanic_dataframe.sibsp.value_counts()[2]
qtd_quatro = titanic_dataframe.sibsp.value_counts()[3]
qtd_cinco = titanic_dataframe.sibsp.value_counts()[4]
qtd_seis = titanic_dataframe.sibsp.value_counts()[5]
qtd_nove = titanic_dataframe.sibsp.value_counts()[8]

print(f"""
Pessoas sozinhas:               {qtd_solo}
Pessoas com um único familiar:  {qtd_par}
Pessoas com dois familiares:     {qtd_trio}
Pessoas com três familiares:      {qtd_quatro}
Pessoas com quatro familiares:    {qtd_cinco}
Pessoas com cinco familiares:     {qtd_seis}
Pessoas com oito familiares:      {qtd_nove}
      """)


Pessoas sozinhas:               283
Pessoas com um único familiar:  110
Pessoas com dois familiares:     14
Pessoas com três familiares:      4
Pessoas com quatro familiares:    4
Pessoas com cinco familiares:     1
Pessoas com oito familiares:      2
      


#### "parch"

In [43]:
titanic_dataframe.parch.unique()

array([0, 1, 3, 2, 4, 6, 5, 9], dtype=uint8)

In [44]:
parch_zero = titanic_dataframe.parch.value_counts()[0]
parch_um = titanic_dataframe.parch.value_counts()[1]
parch_dois = titanic_dataframe.parch.value_counts()[2]
parch_tres = titanic_dataframe.parch.value_counts()[3]
parch_quatro = titanic_dataframe.parch.value_counts()[4]
parch_cinco = titanic_dataframe.parch.value_counts()[5]
parch_seis = titanic_dataframe.parch.value_counts()[6]
parch_nove = titanic_dataframe.parch.value_counts()[9]

print(f"""
Pessoas com bilhete 0: {parch_zero}
Pessoas com bilhete 1:  {parch_um}
Pessoas com bilhete 2:  {parch_dois}
Pessoas com bilhete 3:   {parch_tres}
Pessoas com bilhete 4:   {parch_quatro}
Pessoas com bilhete 5:   {parch_cinco}
Pessoas com bilhete 6:   {parch_seis}
Pessoas com bilhete 9:   {parch_nove}
      """)


Pessoas com bilhete 0: 324
Pessoas com bilhete 1:  52
Pessoas com bilhete 2:  33
Pessoas com bilhete 3:   3
Pessoas com bilhete 4:   2
Pessoas com bilhete 5:   1
Pessoas com bilhete 6:   1
Pessoas com bilhete 9:   2
      


#### Coluna "embarked"

In [45]:
titanic_dataframe.embarked.unique()

array([1, 2, 0], dtype=uint8)

In [46]:
embarque_c = titanic_dataframe.embarked.value_counts()[0]
embarque_q = titanic_dataframe.embarked.value_counts()[1]
embarque_s = titanic_dataframe.embarked.value_counts()[2]

print(f"Número de pessoas que embarcaram pelo portão C: {embarque_c}\nNúmero de pessoas que embarcaram pelo portão Q: {embarque_q}\nNúmero de pessoas que embarcaram pelo portão S: {embarque_s}\n")

Número de pessoas que embarcaram pelo portão C: 102
Número de pessoas que embarcaram pelo portão Q: 46
Número de pessoas que embarcaram pelo portão S: 270



## Aplicação da biblioteca MatPlotLib

### Boxplot

### Gráfico barras

### Gráfico pizza

### Scatterplot